### ISSUE TITLE
Add a new template operator to get info from ezsite_data table

### ISSUE THREAD

**Issue by ernestob** [mugoweb/ezpublish-legacy#34]
A template operator should suit the developer needs of reading information from **ezsite_data** table.

**ezsite_data** is a key/value storage in the eZ Publish database. Adding a template operator will enable a developer to read data from the storage.

We currently can get the information from ezsite_data using eZSiteData class on a module.
Ex.:
```php
$eZSiteDataObj = eZSiteData::fetchByName( 'my_key' ); /* @var $eZSiteDataObj eZSiteData */
if ( $eZSiteDataObj instanceof eZSiteData )
{
    echo( $eZSiteDataObj->attribute( 'value' ) );
}
else
{
    echo( 'The key "my_key" doesn\'t exists' );
}
```

**Comment by pkamps** [comment]
https://github.com/mugoweb/ezpublish-legacy/pull/35

**Comment by pkamps** [comment]
Related pull request have been merged.
